.job_rules: &job_rules
 #the image which will use for this build stage
 #https://git.fxclub.org/alexandria/devops/sbt-build-image
  image:
    name: 895855336803.dkr.ecr.eu-west-1.amazonaws.com/alexandria/dindsbt:0.0.9
  #GitLab runner tag
  tags:
    - alexandria
  #Avoiding pipeline run after git tag stage
  except:
    - tags

    
stages:
  - build
  - tag

build:
  stage: build
  <<: *job_rules
  script:
      #creating artifactory_credentials for using in sbt (variables getting from GiLab alexandria group variables)
      - |
        cat <<EOF > $HOME/.sbt/artifactory_credentials
        realm=Artifactory Realm
        host=lbx.jfrog.io
        user=$JFROG_ARTIFACTORY_SERVICE_USERNAME
        password=$JFROG_ARTIFACTORY_SERVICE_PASSWORD
        EOF
      #sbt stage
      - sbt clean compile package publish

tag:
  stage: tag
  <<: *job_rules
  script:
    - export SERVICE_VERSION=${CI_COMMIT_REF_NAME}-`cat build.sbt | grep "version :=" | awk -F '"' '{print $2}'`
    - git tag $SERVICE_VERSION
    - git push https://$TOKEN_USERNAME:$TOKEN_PASSWORD@$CI_SERVER_HOST/$CI_PROJECT_PATH.git ${SERVICE_VERSION}
